### PR TITLE
fix hebrew display day name.

### PR DESCRIPTION
**Pull request by nadavk72**
for some reason the day 18 appears twice and day 28 is missing.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @nadavk72 thank you very much for this PR. Could you please add a unit test for it as well? Seems like a good way to avoid any future issues.

Thanks!

**Comment by nadavk72** [comment]
Hi @deadprogram, Are you sure that this change worth unit test? it  feels like writing unit test for translation file?
 1=א
2=ב
3=ג
There is no logic involved with my fix ( it feels more like a typo)
Do you agree with me?

**Comment by deadprogram** [comment]
I was thinking more as a "spot check" just to provide some coverage, or something like that.

**Comment by nadavk72** [comment]
hi,
I've modified the current tests to check the heb_day_name.

**Comment by deadprogram** [comment]
תּוֹדָה

Now merging.

**Pull request merged**
